apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: docker-node-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: docker-node-app
  template:
    metadata:
      labels:
        app: docker-node-app
    spec:
      containers:
      - name: docker-node-app
        imagePullPolicy: Always
        image: jonfairbanks/docker-node-app
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: docker-node-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: docker-node-app
  type: LoadBalancer
  externalTrafficPolicy: Local
